<a href="https://colab.research.google.com/github/akanupam/PyTorch-journey/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
print(torch.__version__)


2.6.0+cu124


In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [ ]:
# in pytorch tensors are created using p=torch.tensor()

scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim # dimension

0

In [ ]:
scalar.item()

7

In [ ]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
MATRIX = torch.tensor([[1,2],
                       [3,4]])
MATRIX

tensor([[1, 2],
        [3, 4]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[0]

tensor([1, 2])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
TENSOR = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0][0][0]

tensor(1)

### Random tensors

In [ ]:
random_tensor = torch.rand(6,7)
random_tensor

tensor([[0.6755, 0.8074, 0.7324, 0.9148, 0.8948, 0.2404, 0.5979],
        [0.8206, 0.2558, 0.7156, 0.1603, 0.1701, 0.7281, 0.7230],
        [0.7005, 0.7738, 0.9552, 0.7077, 0.1098, 0.5045, 0.1988],
        [0.6747, 0.4334, 0.4957, 0.4193, 0.5072, 0.7167, 0.1146],
        [0.4878, 0.0100, 0.9821, 0.7618, 0.8201, 0.8996, 0.8204],
        [0.4896, 0.4459, 0.3492, 0.5891, 0.3368, 0.8142, 0.5688]])

In [ ]:
random_tensor.ndim

2

In [ ]:
# create a random tensor with similar shape to an image
random_image_size_tensor = torch.rand(size = (3, 224, 224)) # color, height , witdth of the image 3 colors as we can make any color out of rgb
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

### Zeros and ones

In [ ]:
zeros = torch.zeros(4,6)
zeros

tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])

In [ ]:
ones = torch.ones(6,7)
ones

tensor([[1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

### creating a range of tensors and tensor-like

In [ ]:
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

 3 errors that will be countered in the 1. tensors not right shape
 2. tensors not right device
 3. tensors not right datatype


In [ ]:
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype = None, # what datatype is the tensor it can be float32 float16
                               device= None, # what device the tensor is on "cpu" ,"cuda"
                               requires_grad=False) #  whether or not to track gradients with this tensors operations


In [ ]:
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [ ]:
int_32_tensor = torch.tensor([3,6,8], dtype = torch.int32)
int_32_tensor

tensor([3, 6, 8], dtype=torch.int32)

In [ ]:
int_32_tensor * float_32_tensor

tensor([ 9., 36., 72.])

### getting info from tensors

In [ ]:
some_tensor = torch.rand(3,6)
some_tensor

tensor([[0.2652, 0.5914, 0.2746, 0.4822, 0.4703, 0.4670],
        [0.9277, 0.4696, 0.7760, 0.6117, 0.9171, 0.2660],
        [0.9375, 0.1307, 0.7835, 0.6785, 0.9030, 0.6068]])

In [ ]:
print(some_tensor.dtype)
print(some_tensor.shape)
print(some_tensor.size())
print(some_tensor.device)

torch.float32
torch.Size([3, 6])
torch.Size([3, 6])
cpu


### Manipulating tensors

using mathematical operations

In [ ]:
#create a tensor
tensor = torch.tensor([1,2,3])
tensor+10

tensor([11, 12, 13])

In [ ]:
tensor * 10

tensor([10, 20, 30])

In [ ]:
tensor

tensor([1, 2, 3])

In [ ]:
tensor = tensor +10
tensor

tensor([11, 12, 13])

### matrix multiplication
element wise multiplication<br>
generic mat mul(dot product)

In [ ]:
print(tensor, "*" , tensor)
tensor * tensor

tensor([11, 12, 13]) * tensor([11, 12, 13])


tensor([121, 144, 169])

In [ ]:
torch.matmul(tensor,tensor)

tensor(434)

### transpose can be used as tensor.T


  ### tensor aggregation

In [ ]:
# min max mean sum
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
torch.max(x), x.max()

(tensor(90), tensor(90))

In [ ]:
torch.min(x), x.min()

(tensor(0), tensor(0))

In [ ]:
torch.mean(x.type(torch.float32))
# as mean requires  a float data type


tensor(45.)

In [ ]:
x.type(torch.float32).mean()


tensor(45.)

In [ ]:
#find the sum

torch.sum(x), x.sum()

(tensor(450), tensor(450))

### find positional min and max

In [ ]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
x.argmin()

tensor(0)

In [ ]:
x.argmax()

tensor(9)

In [ ]:
torch.argmin(x)

tensor(0)

In [ ]:
torch.argmax(x)

tensor(9)

### reshaping stacking squeezing and unsqueezing

In [ ]:
import torch
x = torch.arange(1.,10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
x_reshaped = x.reshape(3,3)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [ ]:
#change the view
z= x.view(3,3)
z,z.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [ ]:
#changing z changes x coz they share same memory
z[0][0] = 5
z,x

(tensor([[5., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
#Stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x,x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
#torch.squeeze
x_squeezed = x.squeeze()

In [ ]:
x.squeeze().shape

torch.Size([9])

In [ ]:
x_squeezed

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
x_unsqueezed = x_squeezed.unsqueeze(dim =0)
#changing dim will give different dimension of values
x_unsqueezed

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
# torch.permute
x_original = torch.rand(size = (224,224,3)) # representation of a image in tensors
#permute original tensor

x_permuted = x_original.permute(2,0,1) # shifts axis respectively

print(x_original.shape)
x_permuted.shape

# permute is just like view it shares the same space, however it changes the shape


torch.Size([224, 224, 3])


torch.Size([3, 224, 224])

In [ ]:
x_original

tensor([[[0.0322, 0.0788, 0.8794],
         [0.5888, 0.1180, 0.1399],
         [0.0131, 0.0293, 0.5884],
         ...,
         [0.6791, 0.7244, 0.0015],
         [0.8434, 0.9767, 0.1879],
         [0.4078, 0.1564, 0.0350]],

        [[0.2331, 0.9869, 0.4623],
         [0.2146, 0.7881, 0.3547],
         [0.8475, 0.0132, 0.8415],
         ...,
         [0.1879, 0.4159, 0.6860],
         [0.0037, 0.3900, 0.6721],
         [0.2677, 0.8160, 0.2469]],

        [[0.8881, 0.1950, 0.5912],
         [0.5747, 0.9249, 0.5520],
         [0.3087, 0.9471, 0.3922],
         ...,
         [0.7345, 0.2784, 0.4437],
         [0.6816, 0.2814, 0.5851],
         [0.8267, 0.0587, 0.4662]],

        ...,

        [[0.4756, 0.1843, 0.0645],
         [0.9979, 0.6528, 0.9403],
         [0.3094, 0.9049, 0.4746],
         ...,
         [0.7893, 0.8270, 0.4728],
         [0.1311, 0.7393, 0.9612],
         [0.9580, 0.3630, 0.1573]],

        [[0.2831, 0.3302, 0.3278],
         [0.9992, 0.6101, 0.7522],
         [0.

In [ ]:
x_original[0,0,0]

tensor(0.0322)

In [ ]:
x_permuted[0,0,0] = 7236


In [ ]:
x_original[0,0,0]

tensor(7236.)

# the value in original x changes when there is a change in the permuted one vice-versa

###Indexing(selecting data points from tensors)

In [ ]:
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
x[0][0]

tensor([1, 2, 3])

In [ ]:
x[0][1]

tensor([4, 5, 6])

In [ ]:
x[0][0][1]

tensor(2)

In [ ]:
x[0][2][2]

tensor(9)

In [ ]:
# Use : to select all of the targetted dimension
x[:, 0]

tensor([[1, 2, 3]])

In [ ]:
x[:,:,0]

tensor([[1, 4, 7]])

In [ ]:
x[:,1]

tensor([[4, 5, 6]])

In [ ]:
x[:,:,2]

tensor([[3, 6, 9]])

In [ ]:
x[:,1,1]

tensor([5])

### PyTorch tensors and numpy

In [ ]:
import numpy as np
array = np.arange(1.0,10.0,1)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7., 8., 9.]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float64))

In [ ]:
array = array + 1
array, tensor

(array([ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float64))

In [ ]:
tensor = tensor + 1
array, tensor

(array([ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]),
 tensor([ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=torch.float64))

In [ ]:
tensor.dtype

torch.float64

In [ ]:
array.dtype

dtype('float64')

In [ ]:
#Tensor to numpy
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
tensor = tensor + 1;
numpy_tensor, tensor

(array([1., 1., 1., 1., 1., 1., 1.], dtype=float32),
 tensor([2., 2., 2., 2., 2., 2., 2.]))

### Reproducibility

In [ ]:
# trying to take random from random
# first of all

random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)


tensor([[0.2191, 0.7713, 0.2058, 0.0752],
        [0.5743, 0.0401, 0.4720, 0.6157],
        [0.3975, 0.9317, 0.2999, 0.5928]])
tensor([[0.8818, 0.9265, 0.2749, 0.4762],
        [0.9976, 0.0319, 0.5303, 0.9426],
        [0.2612, 0.6018, 0.7113, 0.6090]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
# Now using torch.manual seed see the magic
# firstly set the random seed

RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED) # you wont see the magic if this line is not included before every torch.rand
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)

print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## running tensors and pytorch objects on gpus

In [ ]:
!nvidia-smi

Sun Apr 27 13:52:25 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   45C    P8             10W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

# check for gpu access

In [ ]:
import torch
torch.cuda.is_available()

True

In [ ]:
#setup device agnostic code

device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
#count number of devices
torch.cuda.device_count()

1

# Putting tensors/models on gpu

In [ ]:
tensor = torch.tensor([1,2,3])

print(tensor,tensor.device)

tensor([1, 2, 3]) cpu


In [ ]:
#move tensor to gpu if available
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

## moving tensors back to cpu

In [ ]:
# if tensor is on gpu it can't transform to numpy
# tensor_on_gpu.numpy()

In [ ]:
tensor_back_on_cpu =  tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [ ]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')